### ISSUE TITLE
No joy

### ISSUE THREAD

**Issue by Zibri** [stylemessiah/GPay-SQLite-Fix#1]
Cleared everything and still google pay and safetynet can detect root.

**Comment by stylemessiah** [comment]
Did you read the README on the main page?

This module should really not be used any longer as a first point of trying to get GPay working, ive been trying to wean people off it (begging people to let it die) for the better part of 2 years now, It only remains as last resort for a number of edged cases where it is the only thing that works for a handful of people....

Please remove it and refer to this post:

https://forum.xda-developers.com/t/discussion-google-pay-magisk-discussion-thread.3906703/post-87481637

This issue will now be closed.....
