### ISSUE TITLE
zip v2.2

### ISSUE THREAD

**Issue by computer777** [stylemessiah/GPay-SQLite-Fix#10]
Does not seem to want to flash on pixel 3xl stock rom.
Um, I'm not the greatest at reporting bugs or issues, what kind of log would you need?

**Comment by ilueckel** [comment]
Same for me on a Xiaomi Mi8 with HavocOS. Magisk is stuck on the flash-screen, but there is no output. Logcat and Magisk logs also have no entries

**Comment by computer777** [comment]
Fixed with latest Magisk release, sorry.

**Comment by computer777** [comment]
Fixed with latest Magisk release, sorry.
