### ISSUE TITLE
NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by Rogi1997** [stylemessiah/GPay-SQLite-Fix#13]
After installing this Module I can not access some sites like Facebook or Twitter

Setup:
Latest official LineageOS with latest OpenGApps
Magisk and HideProps fingerprint and hided from all Google apps

I've testet it on new ROM. 
Flashed all things I need, and I can access these sites.
After flashing this Module I can not access these sites.

![Screenshot_20200805-171326_Chrome](https://user-images.githubusercontent.com/18500093/89430518-1ac12b00-d73f-11ea-82c6-7a53cc763b59.png)
![Screenshot_20200805-171317_Chrome](https://user-images.githubusercontent.com/18500093/89430526-1c8aee80-d73f-11ea-8f0a-e0922d7704bb.png)

**Comment by stylemessiah** [comment]
Never had this issue or had it reported by the other 23,000+ users

This module in no way bloacks domains, or alters security certificates on a device, just doesnt

You can check the script/code yourself....
