### ISSUE TITLE
Android 11 support

### ISSUE THREAD

**Issue by Dunge** [stylemessiah/GPay-SQLite-Fix#15]
This module was working perfectly for me on my Pixel 2 / Android 10 / Magisk. Google Pay was locked, and then after installing the module it was unlocked.

I just updated to Android 11 and Magisk Canary and re-installed the module. No error, but it doesn't seem to work. Still say "Your device doesn't meet security standards" with a note "It may be rooted".

**Comment by stylemessiah** [comment]
Did you follow the (updated) install procees in my original post:  https://forum.xda-developers.com/showpost.php?p=79643248&postcount=176

Please pay extra attention to the Requirements and the Pre-Installation steps (added recently with help from others to avoid exactly the post youre making (with little detail)) - now people are asked to check they pass CTS/basic integrity/evalType BEFORE installing the module. If you cant pass the Pre-Installation steps (and feel free to post which parts of this fail) then youre probably going to be referred to MagiskHide Props Config to (hopefully) address these issue before continuing on to try my module.

The module works for me than just me on Android 11, If CTS/basic integrity/evalType are correctly passing

The module itself has some form of logging for failures on the firstrun after installing (/cache/payfixfirstrun.log). I have no way of helping you before that without you sharing more info, namely what is/isnt passing in the Pre-Installation steps.

As i said, these were added very recently to (hopefully) stop the number of "its not working' posts :)

And as always, XDA golden rule when posting with an issue: If in doubt, more info is betterer! :)

I can say i have the same device and on stock Google Android 11, it worked fine for me, so im not sure why it wouldnt work for you. My cts/evalType passed fine....

From easiest to most tricky: 

* Did you enable MagiskHide in Magisk Canary Manager? 

* Are you also using xposed etc or the other modules already noted to cause issues? - Check the Pre-Installation section for info on these.  

* Have you tried clearing the google play services and play store caches? 

* Did you clean install with wipe the offical Android 11 image or dirty flash? (note: youre on your own if you dirty flashed, i, like many wont support any queries on a dirty flashed ROM)

More info needed

**Comment by Sparh4wk** [comment]
> Did you follow the (updated) install process in my original post: https://forum.xda-developers.com/showpost.php?p=79643248&postcount=176
> 
> Please pay extra attention to the Requirements and the Pre-Installation steps (added recently with help from others to avoid exactly the post youre making (with little detail)) - now people are asked to check they pass CTS/basic integrity/evalType BEFORE installing the module. If you cant pass the Pre-Installation steps (and feel free to post which parts of this fail) then youre probably going to be referred to MagiskHide Props Config to (hopefully) address these issue before continuing on to try my module.
> 
> The module works for me than just me on Android 11, If CTS/basic integrity/evalType are correctly passing
> 
> The module itself has some form of logging for failures on the firstrun after installing (/cache/payfixfirstrun.log). I have no way of helping you before that without you sharing more info, namely what is/isnt passing in the Pre-Installation steps.
> 
> As i said, these were added very recently to (hopefully) stop the number of "its not working' posts :)
> 
> And as always, XDA golden rule when posting with an issue: If in doubt, more info is betterer! :)
> 
> I can say i have the same device and on stock Google Android 11, it worked fine for me, so im not sure why it wouldnt work for you. My cts/evalType passed fine....
> 
> From easiest to most tricky:
> 
> * Did you enable MagiskHide in Magisk Canary Manager?
> * Are you also using xposed etc or the other modules already noted to cause issues? - Check the Pre-Installation section for info on these.
> * Have you tried clearing the google play services and play store caches?
> * Did you clean install with wipe the official Android 11 image or dirty flash? (note: youre on your own if you dirty flashed, i, like many wont support any queries on a dirty flashed ROM)
> 
> More info needed

Hello,

I was able to pass safetynet on my android 11 poco f2 pro.. and I was even able to activate card without using your fix with only magichide.. but I cant use that card for some reason.. Im always geting some error when I wanna use it on terminal.. mb I really need your fix.. but the problem is, that I cant install your universal sqlite binary.. its always greyed out in manager... I was using your fix on android 9 and everything was fine.. thanks for any suggestions and thanks for doing great work!

**Comment by stylemessiah** [comment]
Hi,

Sometimes not even getting everything right with the SQL binary and module will work, sometimes some cards are just unable to make payments at the terminal, due to bank end issues. We've seen this before. Hard to know if this is the case because yuo havent mentioned the error youre getting. If you were able to add without my module, then chances are you didnt need it and its a bank related issue. I would check with your bank. You could also trying hiding your banking app if you have that installed in case thats detecting root.

My SQL Binary only does anything when you initially install it, at that point it runs a script to detect if you need it and where to place it if you do need it. After that its just an entry in the modules list in magisk manager and does nothing.

**Comment by Sparh4wk** [comment]
> Hi,
> 
> Sometimes not even getting everything right with the SQL binary and module will work, sometimes some cards are just unable to make payments at the terminal, due to bank end issues. We've seen this before. Hard to know if this is the case because yuo havent mentioned the error youre getting. If you were able to add without my module, then chances are you didnt need it and its a bank related issue. I would check with your bank. You could also trying hiding your banking app if you have that installed in case thats detecting root.
> 
> My SQL Binary only does anything when you initially install it, at that point it runs a script to detect if you need it and where to place it if you do need it. After that its just an entry in the modules list in magisk manager and does nothing.

Thanks for answer.. card should be fine, cause I was using it for payments yesterday on android 10 with your fix.
I was able to activate my card in google pay just with magisk hide this time.
I saw some error about application not being picked or something, but I will try to get exact error.

**Comment by stylemessiah** [comment]
Best bet is to get the actual error.

Also did you check you were passing SafetyNet via magisk manager?

Android 11 has its foibles, i lasted 2 hours on it before i went back to 10.

So my ability to troubleshoot it on 11 is limited by that.

**Comment by Sparh4wk** [comment]
Ye Im able to past SafetyNet.. I used props module like you mentioned in latest update on xda.
was working like a charm! 👍

**Comment by stylemessiah** [comment]
Good on that front. 

Next and last check - Have you checked that Google Play Store is certified? It can be un-certified even if SafetyNet passes. If its not Certified, put phone in airplane mode,  clear data for Google Play Store and Google Play Services and then reboot and toggle airplane back off i f needed, and check for certification again.

If that passes. yup, last possible method for any further suggestions is to see if you can screencap the actual message or make a note of it

**Comment by Sparh4wk** [comment]
ye were right google play told me that device isnt certified.. after that airplane mode and clearing data, its certified now.. Ill test it tomorrow, mb it will work now.

**Comment by stylemessiah** [comment]
Fingers crossed for you!

**Comment by Sparh4wk** [comment]
well no luck at all.. the error on terminal is "cannot select application" well mb there is something bad with android 11 or dunno
thanks anyway

**Comment by stylemessiah** [comment]
Sounds like its not linking to Google Pay, set to open it. Check your default apps, and see if theres an entry for tap&pay (i cant remember from my 2 hours on 11) and make sure its set to Google Pay....
