### ISSUE TITLE
sqlite3 in termux

### ISSUE THREAD

**Issue by Mexit** [stylemessiah/GPay-SQLite-Fix#5]
I have installed sqlite3 in Termux but was not found.

Please update sqlite3 path from
`/data/data/com.termux/files/usr/lib/sqlite3` 
to 
`/data/data/com.termux/files/usr/bin/sqlite3`

lib --> bin

**Comment by nyetwurk** [comment]
https://github.com/stylemessiah/GPay-SQLite-Fix/pull/1

**Comment by stylemessiah** [comment]
Sorry i havent been on github for a while due to real life, saw this and just updated the install.sh as requested to reflect the paths as listed in above issue...

Apologies for the delay
