### ISSUE TITLE
Notifications not working after applying the fix

### ISSUE THREAD

**Issue by onimaca** [stylemessiah/GPay-SQLite-Fix#6]
Since i installed the SQL-fix i no longer receive notifications for most of the apps like bank, emails, whatsapp business... that were shown before instantly
It seems the fix interferes with push notifications

Is there anyone experiencing same problem. Any idea about how can i solve the issue?

**Comment by stylemessiah** [comment]
I have never had this issue or heard another example of it happening, sorry
