### ISSUE TITLE
Issues flashing in TWRP

### ISSUE THREAD

**Issue by MicrosoftBug** [stylemessiah/GPay-SQLite-Fix#7]
Flashing v1. 7 zip in TWRP on the TicWatch Pro (non-4G) hangs on clearing caches and never installs properly.  Additionally, it doesn't detect that SQLite binary is installed, when, according to Magisk, it is.

**Comment by TNTown** [comment]
I'm having this same issues on my Note9 (Exynos). Install hangs during "clearing caches" and when attempting to reinstall after a clean flash, I received the "missing SQL binary" even though it is installed.

**Comment by stylemessiah** [comment]
It is not meant tt be flashed in TWRP, flash from Magisk Manager....
