### ISSUE TITLE
OR-TAPSH-08 Error

### ISSUE THREAD

**Issue by aagha** [stylemessiah/GPay-SQLite-Fix#9]
Hi -

Added both the SQLite and GPay-SQLite-Fix as Magisk modules and rebooted. Cleared Pay's cache and storage to be safe.

Went to Pay and since I'm logged in, it has a default card associated. I add the code at the back of the card and as it tries to add it, it gives a OR-TAPSH-08 error.

**Comment by jcoelh0** [comment]
That's not an issue of this  project. Talk to google pay's support chat and they can fix it in their system. I guess it's because of too many attempts..

**Comment by aagha** [comment]
You're correct. Thanks. I should have come back and updated/closed.
